name: Daily Cron Job

on:
  schedule:
    - cron: '0 0 * * *' # UTC time => 6:00 AM IST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          STUDENT_EMAILS: ${{ secrets.STUDENT_EMAILS }}
        run: node index.js
